routes:
  myapp:
    httpRoute:
      hostnames:
        - myapp.example.com
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /myapp
          filters:
            - type: URLRewrite
              urlRewrite:
                path:
                  type: ReplacePrefixMatch
                  replacePrefixMatch: /
          backendRefs:
            - name: myapp
